package JavaScript.patches.templates

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with uuid = 'dcf91c6b-4aa4-44ff-a3a2-1b6e9c0b3f40' (id = 'JavaScript_Template')
accordingly, and delete the patch script.
*/
changeTemplate("dcf91c6b-4aa4-44ff-a3a2-1b6e9c0b3f40") {
    expectSteps {
        script {
            name = "Restore NPM Packages"
            id = "RUNNER_6"
            scriptContent = "npm install"
        }
        script {
            name = "Browser Integrated Tests"
            id = "RUNNER_7"
            scriptContent = "npm test -- --single-run --browsers %Browser% --colors false --reporters teamcity"
        }
    }
    steps {
        check(stepsOrder == arrayListOf("RUNNER_6", "RUNNER_7")) {
            "Unexpected build steps order: $stepsOrder"
        }
        stepsOrder = arrayListOf<String>()
    }
}
